### PR TITLE
Upgrading the project settings of Xcode 7, fixing the truncation on email and password signup screens.

### PR DESCRIPTION
**Pull request by ssucharitdas**
PR includes:
- Fixes for Email and Password Truncation on Sign up Page
- Upgrade the project settings, so that deployment target changes are shown.
## Screenshots: iOS 8 with 4S screen  Password

screen shot 2016-05-04 at 11 11 35 am
## Screenshots: iOS 8 with 4S screen Email

screen shot 2016-05-04 at 11 11 22 am

### CODE REVIEW

**Comment by ssucharitdas** [comment]
@marrodriguez @gthackway-mdsol Please review!

**Comment by kbohlmann-mdsol** [comment]
LGTM. Just double checking, you updated the project settings from the automatic process in xcode 7, and now the deployment target is set correctly, and resolves the issue with iqswiftkeyboard deployment target that Marielle had run into?

**Comment by ssucharitdas** [comment]
Yes, it is all automatic project settings update and now it takes the update of deployment target.
It is not complaining about iqswiftkeyboard, once we do a pod install.

**Comment by marrodriguez** [comment]
yes, looks like now it's able to compile and build on an 8.x device! 💯  also the screens (email & password) fixed 👍

**Comment by kbohlmann-mdsol** [comment]
going in! 🐹

**Pull request merged**
